server:
  port: 8888

spring:
  application:
    name: CONFIG-SERVER

  cloud:
    config:
      server:
        git:
          uri: https://github.com/nguyentrongtiencntt/cloud-config-server-user-department
          default-label: main
          bootstrap: false
          clone-on-start: true

