server:
  port: 9030

spring:
  application:
    name: department-server

  config:
    import: "optional:configserver:"
  cloud:
    config:
      uri: http://localhost:8888/department-service/default